# black or 0 | red or 1
# green or 2 | yellow or 3
# blue or 4  | magenta or 5
# cyan or 6  | white or 7
BULLETTRAIN_PROMPT_CHAR='λ'
BULLETTRAIN_PROMPT_ROOT=true
BULLETTRAIN_PROMPT_SEPARATE_LINE=true
BULLETTRAIN_PROMPT_ADD_NEWLINE=true

BULLETTRAIN_STATUS_SHOW=true
BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_STATUS_BG='green'
BULLETTRAIN_STATUS_ERROR_BG='red'
BULLETTRAIN_STATUS_FG='black'

BULLETTRAIN_TIME_SHOW=true
BULLETTRAIN_TIME_12HR=false
BULLETTRAIN_TIME_BG='cyan'
BULLETTRAIN_TIME_FG='white'

BULLETTRAIN_CUSTOM_MSG=false
BULLETTRAIN_CUSTOM_BG='white'
BULLETTRAIN_CUSTOM_FG='black'

BULLETTRAIN_CONTEXT_SHOW=true
BULLETTRAIN_CONTEXT_BG='black'
BULLETTRAIN_CONTEXT_FG='white'
#BULLETTRAIN_CONTEXT_DEFAULT_USER=
#BULLETTRAIN_CONTEXT_HOSTNAME=
#BULLETTRAIN_IS_SSH_CLIENT=

BULLETTRAIN_VIRTUALENV_SHOW=false
BULLETTRAIN_VIRTUALENV_BG='yellow'
BULLETTRAIN_VIRTUALENV_FG='white'
BULLETTRAIN_VIRTUALENV_PREFIX='🐍'

BULLETTRAIN_NVM_SHOW=false
BULLETTRAIN_NVM_BG='green'
BULLETTRAIN_NVM_FG='white'
BULLETTRAIN_NVM_PREFIX='⬡'

BULLETTRAIN_RUBY_SHOW=false
BULLETTRAIN_RUBY_BG='magenta'
BULLETTRAIN_RUBY_FG='white'
BULLETTRAIN_RUBY_PREFIX="♦"

BULLETTRAIN_GO_SHOW=false
BULLETTRAIN_GO_BG='blue'
BULLETTRAIN_GO_FG='white'
BULLETTRAIN_GO_PREFIX='go'

BULLETTRAIN_PERL_SHOW=false
BULLETTRAIN_PERL_BG='yellow'
BULLETTRAIN_PERL_FG='black'
BULLETTRAIN_PERL_PREFIX='🐪'

BULLETTRAIN_DIR_SHOW=true
BULLETTRAIN_DIR_BG='blue'
BULLETTRAIN_DIR_FG='white'
BULLETTRAIN_DIR_CONTEXT_SHOW=false
BULLETTRAIN_DIR_EXTENDED=1

BULLETTRAIN_EXEC_TIME_SHOW=false
BULLETTRAIN_EXEC_TIME_ELAPSED=5
BULLETTRAIN_EXEC_TIME_BG='yellow'
BULLETTRAIN_EXEC_TIME_FG='black'

BULLETTRAIN_GIT_SHOW=true
BULLETTRAIN_GIT_COLORIZE_DIRTY=false
BULLETTRAIN_GIT_COLORIZE_DIRTY_BG_COLOR='white'
BULLETTRAIN_GIT_COLORIZE_DIRTY_FG_COLOR='white'
BULLETTRAIN_GIT_BG='white'
BULLETTRAIN_GIT_FG='black'
#BULLETTRAIN_GIT_PROMPT_CMD=git_prompt_info
BULLETTRAIN_GIT_EXTENDED=true
BULLETTRAIN_GIT_PREFIX=' '
BULLETTRAIN_GIT_SUFFIX=' '
BULLETTRAIN_GIT_DIRTY=''
BULLETTRAIN_GIT_CLEAN=''
BULLETTRAIN_GIT_ADDED='%F{green}✚%F{black}'
BULLETTRAIN_GIT_MODIFIED='%F{blue}✹%F{black}'
BULLETTRAIN_GIT_DELETED='%F{red}✖%F{black}'
BULLETTRAIN_GIT_UNTRACKED="%F{cyan}✭%F{black}"
BULLETTRAIN_GIT_RENAMED='➜'
BULLETTRAIN_GIT_UNMERGED='═'
BULLETTRAIN_GIT_AHEAD='⬆'
BULLETTRAIN_GIT_BEHIND='⬇'
BULLETTRAIN_GIT_DIVERGED='⬍'

BULLETTRAIN_PROMPT_ORDER=(
	context
	dir
	git
	status
)
